spring:
  config:
    import: application-secret.yml

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 24
      minimum-idle: 24
      connection-init-sql: SELECT 1

  jpa:
    show-sql: true
    database: mysql
    hibernate:
      ddl-auto: update
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

logging:
  config: classpath:logback-spring.xml
